/**
 * !! IMPORTANT !!
 * This file is automatically generated by GitHub Actions during deployment
 * using the configuration sent from Google Apps Script.
 * Do not store real API URLs or LIFF IDs in this file in version control (.git).
 */
const CONFIG = {
    API_URL: "AUTO_GENERATED_BY_GITHUB_ACTIONS",
    LIFF_ID: "AUTO_GENERATED_BY_GITHUB_ACTIONS"
};
